cloud:
  aws:
    credentials:
      access-key: <Provide ur access key>
      secret-key: <provide ur secret key>
    region:
      static: us-east-1
    stack:
      auto: false

application:
  bucket:
    name: procorp-assets


spring:
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 10MB
      max-file-size: 10MB
      max-request-size: 10MB